resolver: lts-5.12

packages:
- '../api'
- '.'
- location:
    git: https://github.com/lethom/auth-identity.git
    commit: 6d7d159a4c47e0872dc0bb06de59efea01089771
extra-deps:
  - servant-0.7.1
  - servant-server-0.7.1
  - servant-client-0.7.1
flags: {}
extra-package-dbs: []
